title: Anton Rassolenko # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  SW Developer 
  <br>
  Java/Kotlin/Go, Python, Flutter/Dart,  C++ ,JavaScript, PHP, HTML/CSS
  <br>
  <br>
  QA 
  <br>
  Katalon, Appium, Selenium
  <br>
  <br>
  <a href="https://www.linkedin.com/in/anton-rassolenko-a903697b/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-1239769-7 # your Google Analytics tracking ID here
